### PR TITLE
[FIX] Missing Custom Fields in Welcome Event due to race condition

### LINKED ISSUE #895: [Investigate][PRIORITIZE] appName and or token empty at times

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/895

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 201 files?  Is that correct?

**Comment by Shailesh351** [comment]
@ear-dev yeah, build files🙂 Check commits if you want to check exact code change. I keep all build file changes in separate commit

**Comment by ear-dev** [comment]
Gottit...  thanks @Shailesh351

**Comment by ear-dev** [comment]
@Shailesh351 this looks good.  Thanks!  I'll merge it soon, and make the RC PR to pick it up

**Review by ear-dev — APPROVED** [review]

**Pull request merged**
