### PR TITLE
[FIX] Special Characters in Messages show in Unicode 

### LINKED ISSUE #1308: [Bug] some characters not handled correctly in the client side widget
This must have to do with the new livechat message parser which converts characters. 

In this conversation I was typing the word "I'm"

image

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Closes: https://github.com/WideChat/Rocket.Chat/issues/1308

Reverts: https://github.com/RocketChat/Rocket.Chat.Livechat/pull/701

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis I tested this and it looks good.  We can merge after @Shailesh351 takes a quick look.  Thanks.

**Comment by csmith14** [comment]
This looks like it doesn't address pasted/dropped text, as the handlers for those actions still use the `parse` function: 
- https://github.com/WideChat/Rocket.Chat.Livechat/blob/master/src/components/Composer/index.js#L79
- https://github.com/WideChat/Rocket.Chat.Livechat/blob/master/src/components/Composer/index.js#L102

**Comment by ear-dev** [comment]
> This looks like it doesn't address pasted/dropped text, as the handlers for those actions still use the `parse` function:
> 
> * https://github.com/WideChat/Rocket.Chat.Livechat/blob/master/src/components/Composer/index.js#L79
> * https://github.com/WideChat/Rocket.Chat.Livechat/blob/master/src/components/Composer/index.js#L102

I did just test cut and paste into a widget with this fix and it seemed to work fine.  I used "I'm testing"  because I know that apostrophe was a problem.  Are there other good characters I can test?

**Comment by csmith14** [comment]
Huh, okay maybe those handlers don't do exactly what their name implies?
Here's the character map used for replacements:

```
const escapeMap = {
	'&': '&amp;',
	'<': '&lt;',
	'>': '&gt;',
	'"': '&quot;',
	'\'': '&#x27;',
	'`': '&#x60;',
};
```

**Comment by AlexanderKanakis** [comment]
New commit will deal the the issue @csmith14 found. Made sure that the text is still parsed upon submission, so it is clean.

**Comment by ear-dev** [comment]
I tested the latest and it looks good to me.... @csmith14 ?

**Review by csmith14 — APPROVED** [review]

**Pull request merged**
