### PR TITLE
[Feature] Add ability to push logs to ES

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Rocket.Chat server PR -> https://github.com/WideChat/Rocket.Chat/pull/985

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya can you fix the conflicts please?
@Shailesh351 can you review please?

thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev @Shailesh351 PR updated with signature4 authentication and conflicts fixed

**Comment by ear-dev** [comment]
@bhardwajaditya Are we still missing a text box in the AdminUI for "access key id"?

image

**Comment by bhardwajaditya** [comment]
@ear-dev Sorry forgot to push the changes, committed in my local, forgot to push server changes. Pushed them just now.

**Comment by ear-dev** [comment]
@bhardwajaditya do we actually need the Livechat_elastic_search_token field?

image

**Comment by ear-dev** [comment]
@bhardwajaditya do we actually need the Livechat_elastic_search_token field?

image

**Review by ear-dev — APPROVED** [review]

**Pull request merged**
