### PR TITLE
Handle session trigger and registeredOnly in triggers

### LINKED ISSUE #35: [IMPROVE] Trigger welcome event after registration page, when registration page is enabled
We have our great livechat session-start trigger that was recently added. The dialogflow app uses it to trigger a welcome event when the widget is first opened.

improve this session-start feature to send the welcome event after the registration page is filled out (when registration page is enabled, otherwise send it on widget opening) 

Another note:
When someone ends the chat, then clicks 'new chat', the welcome event should fire again

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #35 #38

### CODE REVIEW

**Comment by dlassalle** [comment]
Using these two branches, the re-open with a new chat issue is resolved, but I'm not having success triggering the welcome event when i have both a page with a registration form and a page without the registration page both being active at the same time using 'Skip Registration Form on Domains' under Admin -> Omnichannel -> livechat settings

**Comment by shubhsherl** [comment]
@dlassalle Fixed the issue

**Comment by dlassalle** [comment]
@shubhsherl @Shailesh351 im trying to test this, but the skip registration domain setting doesnt seem to be working at all
https://github.com/WideChat/Rocket.Chat/pull/381
The only one i can get to work on livechat.viasatconnect.com is to enter 'livechat.viasatconnect.com', but this then skips everywhere, including my 'localhost:5000/admin/test_client' address that im using
Im trying to get 'livechat.viasatconnect.com/livechat' to show the reg page, but skip it on localhost

**Comment by Shailesh351** [comment]
> Im trying to get 'livechat.viasatconnect.com/livechat' to show the reg page, but skip it on localhost

In this case you can only mention localhost in the list, so it will only skip on localhost.

From the PR 381:
Adding only domain name skips registration for all paths with that domain
i.e. if www.google.com it will skip for www.google.com/a,www.google.com/b, www.google.com/*
Adding specific path like www.google.com/a will only skip registration on that path not others

**Comment by dlassalle** [comment]
Cant test this entirely due to https://github.com/WideChat/Rocket.Chat.Livechat/issues/41, will continue debugging on that issue

**Comment by ear-dev** [comment]
Prajval approved.

**Pull request merged**
