### PR TITLE
[IMPROVE] Simplify path for closing chat on widget

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
After Visitor confirms they want to close their chat the chat closes without the extra close chat button.

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis please adjust so that when the session times out the window remains open.

**Comment by ear-dev** [comment]
@AlexanderKanakis I can't yet get this to work....  I adjusted package.json to point to this livechat branch, and built the server locally, but I'm still seeing the same behavior we have always had.  Am I missing something?  Is this PR completely up to date with all of your changes?  Thanks.

**Comment by AlexanderKanakis** [comment]
@ear-dev This is odd. Can you test the widget individually in a local host?

**Comment by ear-dev** [comment]
@Shailesh351 Alexander has added the build files to this PR, but it is still not working properly for me when I try to run it locally, after updating my package.json and package-lock.json files and repopulating node_modules on my local.  Do you see anything wrong with the way he might have added the build files?

Currently I'm just getting a blank screen when I go to localhost:3000/livechat

Thanks.

**Comment by Shailesh351** [comment]
@ear-dev I have added commit for updating build files in this PR using `yarn build`

**Comment by ear-dev** [comment]
@AlexanderKanakis I finally got this to work......  looks good!  I'll merge.

**Pull request merged**
