### PR TITLE
Fix Start Session, Chat Finished Message, Remove Not/Connected banner

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes 
- Need to start session after user clicks on the icon, not when the page is loaded. https://github.com/WideChat/Rocket.Chat/issues/693
- Conversation Finished Message consistency https://github.com/WideChat/Rocket.Chat/issues/675
- Remove the "livechat * connected" banners entirely. https://github.com/WideChat/Rocket.Chat/issues/697

### Configure as below

Screenshot 2021-05-21 at 7 03 45 PM

Screenshot 2021-05-21 at 7 04 20 PM

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 I am trying to add a new trigger in Omnichannel/Triggers on the livechat.viasatconnect.com server, but it is not offering me the 'Save' button.  Any ideas?

**Comment by ear-dev** [comment]
@Shailesh351 After testing successfully for a while I seem to have gotten into a bad state that I can't get out of.....  any ideas?
image

**Comment by Shailesh351** [comment]
Can you check the response? Is it Too many requests?

**Comment by ear-dev** [comment]
@Shailesh351 All I can see is 400 response.....  the RC server is throwing this:

API ➔ debug Failure {                                                                                                            
I20210521-17:19:13.324(0)?   statusCode: 400,                                                                                                               
I20210521-17:19:13.325(0)?   body: TypeError: Cannot read property '_id' of undefined                                                                       
I20210521-17:19:13.325(0)?       at Messages.createWithTypeRoomIdMessageAndUser (app/models/server/models/Messages.js:789:15)                               
I20210521-17:19:13.325(0)?       at Messages.createCommandWithRoomIdAndUser (app/models/server/models/Messages.js:902:15)                                   
I20210521-17:19:13.325(0)?       at Object.assignAgent (app/livechat/server/lib/RoutingManager.js:76:12)                                                    
I20210521-17:19:13.325(0)?       at app/livechat/server/lib/RoutingManager.js:146:20
I20210521-17:19:13.326(0)?       at /home/ubuntu/.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modu$es/meteor-promise/fiber_pool.js:43:40
I20210521-17:19:13.334(0)?    => awaited here:

**Comment by chadgoss** [comment]
tested and verified

**Pull request merged**
