### PR TITLE
Fix composer state on start and chat close

### LINKED ISSUE #892: [BUG][ResUS-UX] stuck at "Starting chat" when opening a new tab after "please close this window"
to reproduce:
 1) Start chat and get to the state where bot sends "Please close this window" 
2) Go back(back arrorw) on mobile 
3) Again click "Chat now"

PR Link - https://github.com/WideChat/Rocket.Chat.Livechat/pull/101

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes https://github.com/WideChat/Rocket.Chat/issues/892 and https://github.com/WideChat/Rocket.Chat/issues/903 and https://github.com/WideChat/Rocket.Chat/issues/905

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya I should be able to test this on my local machine, right?  It almost seems like the composer is not being disabled at all now...  so it's just not working for me.  Can you verify and maybe send a video of it working please?  Thanks.

**Comment by ear-dev** [comment]
@bhardwajaditya Please disregard my previous comment.....  I think I was using an old version of DF.app, and after upgrading it is now working......  I will continue to test.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev can you test the escalated queue bug as well, I don't see it post this fix, may be this fixed it.

**Comment by ear-dev** [comment]
@bhardwajaditya seems like we have a bug in this PR where the 'starting chat' button gets stuck across sessions....  are you able to reproduce this?


https://user-images.githubusercontent.com/28864717/131015447-076711d9-4f85-4396-bf18-ed162c16ee0a.mov

**Comment by bhardwajaditya** [comment]
@ear-dev fixed the bug with the latest commit

**Review by ear-dev — APPROVED** [review]
@bhardwajaditya this looks good..  works great....  I'm going to merge

**Pull request merged**
