### PR TITLE
Fix agent icon for messages and header

### LINKED ISSUE #1177: [SF.agent] Change the user icon to match the salesforce agents name.
We would like to use the first letter of the name, like the default RC username icon behavior.  This needs to be scoped specifically to just the current session, not a global change of the SF.app.bot username.

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes: https://github.com/WideChat/Rocket.Chat/issues/1177

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya this works great!  I tested the two tab scenario as well and saw no issues.  Thanks.  @Shailesh351 can you review please?

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya @ear-dev This is also affecting DF Bot Icon. Is it expected behaviour?

Before

Screenshot 2022-06-16 at 5 14 56 PM

After

Screenshot 2022-06-16 at 5 16 38 PM

**Comment by ear-dev** [comment]
great catch...  @Shailesh351 no, that is not the desired behavior.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev @Shailesh351 fixed the bug, now it will be enabled only when salesforce agent name is available.

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya @ear-dev I'm having some issue with my local setup. Agent Name is not updating at all. But from the PR changes, it looks good.

@ear-dev Can you confirm if it's working for you? I will check what's wrong with my setup

UPDATE: The issue is intermittent so there definitely something wrong. We are not receiving salesforceAgentName customField sometimes

**Comment by ear-dev** [comment]
@Shailesh351 @bhardwajaditya I will also test this....  but Shailesh, are you maybe seeing the WebSocket vs. RESt issue that was meant to be fixed in the other PR?  https://github.com/WideChat/Rocket.Chat.Livechat/pull/150

@bhardwajaditya is this PR currently up to date with that fix?  Seems like it should be, right?

**Comment by ear-dev** [comment]
I tested and it looks good to me.....  all working as designed.

**Review by ear-dev — APPROVED** [review]

**Pull request merged**
