### PR TITLE
[FIX] Chat Issues in Multiple Tabs

### LINKED ISSUE #1149: [Two Tab issue] Verify that two or more tabs open to the widget are in sync in regard to the Feedback Survey.
Repro:
- tab1 escalates, agent closes the session, Feedback Survey button appears.  Minimize the widget.
- open tab2, talk to the DF bot and close the session without escalation.

Result:
- tab2 looks fine, chat is closed no Feedback Survey.
- tab1 the chat is closed, but the Feedback Survey button is showing.

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/1149

@ear-dev This also fixes old chat remains in the chat in the multiple tabs case. We need to test all the scenarios after this, timeout as well

### CODE REVIEW

**Comment by ear-dev** [comment]
Thanks @Shailesh351 I'll load this up today and give it a try.

**Comment by ear-dev** [comment]
@bhardwajaditya can you do a quick review on this PR please if you have a minute?  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev sure doing it

**Comment by ear-dev** [comment]
@Shailesh351  So far I see one small issue:

1. Open chat in two tabs
2. Close chat with 'X' in tab2, then minimize the widget in the same tab.  At this point it looks good, both tabs appear in sync.
3. Click the widget in tab1 and the transcript is visible, but we expect the 'New Chat' screen.  If you click the widget in tab2 then you do get the 'New Chat' screen as expected, and now both tabs are in sync again.

Is this something easy to fix?  Thanks.....

**Comment by Shailesh351** [comment]
@ear-dev It will need some time for debugging. We can fix it separately. Looks like all the major issues are now gone.

**Review by bhardwajaditya — APPROVED** [review]
@ear-dev the changes look good to me from the code point of view, not considering the issue you just mentioned

**Comment by ear-dev** [comment]
Thanks @bhardwajaditya 
@Shailesh351 ready to merge this then?

**Comment by Shailesh351** [comment]
Yup @ear-dev All good!

**Pull request merged**
