### PR TITLE
Chore: Remove Character Limit Counter on Disabled Composer

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
For issue: https://github.com/WideChat/Rocket.Chat/issues/1164

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis can you verify please that this PR works for you?  I'm getting an error in the console which is preventing the widget from loading....  

image

**Comment by AlexanderKanakis** [comment]
https://user-images.githubusercontent.com/18405180/167652116-e8a8bc88-c986-4e6d-9e02-673512c7efa5.mp4

Try again with the new build files please.

**Comment by ear-dev** [comment]
@AlexanderKanakis this is working now.  Looks good. Is it possible to tie the character counter to the 'enable_typing' flag?  i.e. never show the counter when the composer is disabled?  I know I had signed off on only removing the counter after close chat, but looking at it now, I think it would be better to remove the counter in all cases when the composer is not available to the visitor.  Thanks.  Sorry about the confusion.

**Review by ear-dev — APPROVED** [review]
looks good... thanks.

**Pull request merged**
