### PR TITLE
Add disable input feature

### LINKED ISSUE #9: [FEATURE REQUEST] Allow for disabling of user input if message attachment payload exists
- When a bot service sends a payload for disabling input, the user't text-entry box should be greyed out and display the `disabpleInputMessage` string
- The input should be disabled as long as the most recent message from the agent/bot contains the disable payload, any message that does not have the disable payload should remove the input block

Example payload
```
{
  "disableInputMessage": "Please wait",
  "disableInput": true
}
```

- This payload would be added as a message attachment  of type 'action' in client

Screenshots of another client's performance:

Screen Shot 2020-07-01 at 8 16 12 AM
Screen Shot 2020-07-01 at 8 16 31 AM

These payloads will be added as part of https://github.com/RocketChat/Apps.Dialogflow/issues/29, so it may be the coming from custom-field rather than attachments..

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes https://github.com/WideChat/Rocket.Chat.Livechat/issues/9

### CODE REVIEW

**Comment by shubhsherl** [comment]
2020-09-14-162236_1135x823_scrot

**Comment by dlassalle** [comment]
Do you have any steps to test this feature?
looks like https://github.com/RocketChat/Apps.Dialogflow/issues/40 is in progress on our fork, if we can get that to parse our payloads then i can test this easier using the bot

**Comment by shubhsherl** [comment]
@dlassalle You can test this easily from the agent side
Run the following command from terminal:
```
curl -H "X-Auth-Token: <MeteorLoginToken>" \
     -H "X-User-Id: <MeteorUserID>" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/chat.sendMessage \
 -d '{
   "message": {
      "rid": "<livechatRoomID>",
      "msg": "Sample  new message",
      "customFields": {"disableInput": true, "disableInputMessage": "Please wait"},
      "attachments": [
    {
      "title": "text button with url",
      "actions": [
        {
          "type": "button",
          "text": "randomWord",
          "msg": "randomWord", "msg_processing_type":"sendMessage", "msg_in_chat_window": true
        }
      ]
    }
  ]
  }
}'
```
OR
```
curl -H "X-Auth-Token: <MeteorLoginToken>" \
     -H "X-User-Id: <MeteorUserID>" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/chat.sendMessage \
 -d '{
   "message": {
      "rid": "adqApg3NsCqyzsyk6",
      "msg": "Sample  new message",                                                                     
      "attachments": [
    {
      "title": "text button with url",
      "actions": [
        {
          "type": "button",
          "text": "randomWord",
          "msg": "randomWord", 
          "msg_processing_type": "sendMessage", 
          "msg_in_chat_window": true, 
          "disableInputMessage": "Input is disabled, please refer the above message", 
          "disableInput": true
        }
      ]
    }
  ]
  }
}'
```

**Comment by dlassalle** [comment]
tested using dl_test on livechat.viasatconnect.com (using latest develop_pwa) results in input still being entered, but none of the buttons work and there is nothing displayed (the quick-reply buttons do appear to send messages to dialogflow still, though
Screen Shot 2020-09-15 at 10 59 49 AM

**Comment by shubhsherl** [comment]
@dlassalle I am seeing the issue on livechat.viasat deployment. Will debug and fix it.

**Comment by shubhsherl** [comment]
@dlassalle There is a new field in message payload called `blocks`. It uses the UIkit to render and message actions. Do we want to use blocks for message actions too(actions in attachment)? Also, should we check the `disableInput` in block payload?
```
{
blocks: [{
       type: "actions",
       appId: "21b7d3ba-031b-41d9-8ff2-fbbfa081ae90"
       blockId: "e9b161f0-f8a5-11ea-a22e-05fda1c9db7f"
       elements: [ {actionId: "cd5f7f15-ea6e-4808-ab21-07381f2193e4"
                 text: {text: "test1", type: "plain_text"}
                 type: "button"
                 value: "test1"
                 }]
}]
channels: []
mentions: []
msg: ""
rid: "tMEvxbFZkqg5W6a49"
ts: "2020-09-17T05:23:26.234Z"
}
```

**Comment by shubhsherl** [comment]
@dlassalle The issue is not reproducible locally, though, from console error, I think the issue should be fixed by the above commit. Can you confirm?

**Review by dlassalle — APPROVED** [review]

**Comment by dlassalle** [comment]
@shubhsherl Looks to have fixed my issues.
in regard to the blocks - I dont have much of an opinion.. as long as https://github.com/RocketChat/Apps.Dialogflow/issues/40 allows me to add a simple payload to the dialogflow bot then I'm happy

**Pull request merged**
