### PR TITLE
Handle 'open-chat-window' trigger

### LINKED ISSUE #8: [FEATURE REQUEST] Add Omnichannel Livechat Trigger option for when user opens the chat window
Usually when the widget is first opened to a text dialog, its a blank box without an agent present. Only when the user types their first message does it route to an agent.

Add an option enabling agents (and bots) to type first. For example, when a user opens the widget for the first time, they see a message from the bot saying "Thanks for contacting us, please describe your issue"

Additionally, add an 'Action' option to actually start a session and assign an agent without the user typing something first. The opening text message doesnt need to be included in the new action

-------------------------------------

if this requires changes to the RC core, please use our fork with the develop_livechat branch https://github.com/WideChat/Rocket.Chat/tree/develop_livechat

### PR DESCRIPTION
**Pull request by shubhsherl**
Closes #8 
RC Server PR: https://github.com/WideChat/Rocket.Chat/pull/384

### CODE REVIEW

**Comment by dlassalle** [comment]
This looks good as a first step for that issue, there was an additional ask on that issue that may have been written poorly, ive updated it.
We need to add an 'Action' to actually start a session, rather than just look like a session started

**Comment by dlassalle** [comment]
@shubhsherl Looks like we are right about there, however I get this error showing up everytime i open a new session:
Screen Shot 2020-08-27 at 1 35 32 PM

**Comment by shubhsherl** [comment]
@dlassalle I am unable to reproduce the error, can you provide the steps to reproduce?

**Comment by dlassalle** [comment]
I can't figure out exactly what is going on, but using the /livechat endpoint works, and `yarn dev` works, but when you embed the widget in a test webpage it creates the alert.
This is using a local server with both the dialogflow/salesforce apps installed as they are in our livechat.viasatconnect.com is

**Comment by shubhsherl** [comment]
@dlassalle I have fixed the issue. Please review again . Thanks

**Pull request merged**
