### PR TITLE
[Fix] Remove Composer on Close

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Remove composer and "Finish Chat" button in options instead of whole footer.

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis I'm not able to load the widget while testing this PR.  I see this error in the console:
image

Can you verify that it works for you?  Thanks...

**Comment by AlexanderKanakis** [comment]
> @AlexanderKanakis I'm not able to load the widget while testing this PR. I see this error in the console: image
> 
> Can you verify that it works for you? Thanks...

The widget runs runs with Rocket.Chat.Livechat branch `remove_composer_on_close` and Rocket.Chat branch `develop_pwa`

**Comment by ear-dev** [comment]
@AlexanderKanakis interesting.....  I was testing with one of your new, api branches.....  I'll move to develop_pwa and test again.

**Comment by ear-dev** [comment]
looks good.  thanks.

**Pull request merged**
