### PR TITLE
[EXTEND] Remove Composer on Closed Chat

### PR DESCRIPTION
**Pull request by AlexanderKanakis**

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis what did we decide about mobile, do you remember?  I think we do not want this feature in mobile?

**Comment by AlexanderKanakis** [comment]
@ear-dev Removed feature for mobile

**Comment by ear-dev** [comment]
@bhardwajaditya can you review please?  I tested and it looks good to me.  Thanks.

**Comment by bhardwajaditya** [comment]
> @bhardwajaditya can you review please?  I tested and it looks good to me.  Thanks. 

Sure @ear-dev will do that

**Review by bhardwajaditya — APPROVED** [review]
@ear-dev changes look good to me, I have tested multi tab scenarios as well and works fine

**Comment by Shailesh351** [comment]
@ear-dev @AlexanderKanakis Just noticed, this also removes the `Print Chat` option after chat is closed. Is it expected?

**Comment by ear-dev** [comment]
> @ear-dev @AlexanderKanakis Just noticed, this also removes the `Print Chat` option after chat is closed. Is it expected?

I'll make story to track this and fix.

**Pull request merged**
