### PR TITLE
[Upstream Catchup] Merge Rocket.chat.Livechat:develop to develop

### PR DESCRIPTION
**Pull request by ear-dev**
Weekly Catchup PR to merge Rocket.chat.Livechat:develop in develop.

### CODE REVIEW

**Review by Shailesh351 — COMMENTED** [review]
@AlexanderKanakis While testing the widget, it is not even starting the chat. Is it working for you? 

Screenshot 2022-08-29 at 4 56 19 PM

**Comment by AlexanderKanakis** [comment]
@Shailesh351 Cannot replicate the missing `AudioAttachment` path error.

**Review by Shailesh351 — APPROVED** [review]

**Comment by ear-dev** [comment]
@AlexanderKanakis I am not getting the "Save Transcript" button at the end of a livechat session.  Can you verify please if you are seeing it?  Thanks.

**Review by Shailesh351 — COMMENTED** [review]
@AlexanderKanakis I can see there are 16 occurrences of `message.t` which need to be renamed to `message.type`? Can you please confirm and update it? Thanks...

**Comment by ear-dev** [comment]
@AlexanderKanakis looks like there is something wrong with the user icon handling in this PR?

image

**Comment by ear-dev** [comment]
@AlexanderKanakis my cypress tests are acting strange because the selector for the message list does not seem to be finding the last message.  I notice what I think is a new feature:  `message drop overlay` or something like that.  Can you check the commits for any new feature in livechat that may have added the ability to drag and drop an image anywhere onto the chat window?  Thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis my 'give feedback' button at the end of an escalated chat looks weird.  Can you take a look please and verify if it's the same for you?

image

**Comment by ear-dev** [comment]
@AlexanderKanakis we figured out the weird cypress test behavior issue, and I am able to adjust on the cypress side.  Basically upstream added this new method, which was re-encoding message text, and that was not matching the text definitions I had created in Sublime.  Thanks. 

https://github.com/WideChat/Rocket.Chat.Livechat/blob/4687ea268f9eebed91e61e0ae4d5d0f6f609fb1c/src/components/helpers.js#L297

**Comment by ear-dev** [comment]
ok, this passed all the tests one I fixed the cypress thing.  Thanks @AlexanderKanakis, I'll merge.

**Pull request merged**
