### PR TITLE
[EXTEND] Check idleTimeoutHandler on Widget to close chat from Widget/App

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Restored client setInterval function for warning countdown, but disabled closechat functionality when idleTimeoutHandler from customFields is set as "app".

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis please refactor so that we do not invoke the timer when the handler == 'widget'.  All we need to invoke is the countdown banner when the time is up.

**Comment by chadgoss** [comment]
@AlexanderKanakis can you resolve the conflict? thanks!

**Comment by AlexanderKanakis** [comment]
@ear-dev @chadgoss 

1. Solved Confict issue
2. The widget uses only one timer for both the warning and the timeout. Changed conditional branch to a more appropriate position.
3. Fixed an issue that prevented the client window from closing chat even when the salesforce agent had already been given a timeout.

**Comment by ear-dev** [comment]
@AlexanderKanakis can you fix this file conflict please?

And, I'm not sure if you need to push new build files after you do that?

**Comment by ear-dev** [comment]
@AlexanderKanakis can you add the build files to this PR please?  I need them to test....  thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis 
I'm still trying to test these timeoutHandler PRs....... but running into issues
I'm running an instance of RocketChat server locally on my laptop, but have configured livechat in package.json and package-lock.json to use your branch in the build
but when I navigate to http://localhost:3000/livechat the widget does not show up
and I can see this error in the console:

image

any idea what that might be about?
can you also try building RC server with your branch of livechat and let me know if you can reach the widget on the /livechat path?

**Comment by ear-dev** [comment]
@AlexanderKanakis I am finally able to test these two PRs.....  and the session timeout warning timer is visible in the widget, and the salesforce case is getting closed.  However, after I get the popup dialog on the widget, and I close the chat with it, I am brought back to the widget and the composer is still available for typing. 

In this case, after the timer goes off and the session is closed, the composer should be disabled with the "Please close this chat" message........  or even better, the widget itself should just close so that we are back at the "New Chat" view.  

Can you fix?

thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis can you take a look at the conflicting file please?

**Comment by ear-dev** [comment]
@AlexanderKanakis I can see that the last commit to this branch was a merge from develop.  But I think that you will also need to add new build files, yet again, after every new commit like this?  Thanks.

**Comment by AlexanderKanakis** [comment]
@ear-dev I used `yarn start` and `yarn build` to generate new build files after merging. Double-checked right now to make sure. These are the only changes in the build files.

**Comment by ear-dev** [comment]
@AlexanderKanakis I'm still seeing the same behavior where I can type in the composer after the chat is closed.  In fact, there is no indication in the transcript that the chat has been closed.  Can you double check again please that all the build files are correct, or test again yourself with exactly what's checked into git please?  Thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis I'm still seeing the same behavior where I can type into the composer after the chat has been closed.  And there is also no indication in the transcript that the chat is closed.  Can you double check and test again, using exactly the code that is checked into your branch in git please?  And we're sure all the build files are correct?  Thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis Shailesh's PR for fixing the scheduled task handling in SF app is looking good.  Can you resolve these conflicts and push new build files please?  We need this PR in order to show the timeout warning banner when the app is configured to use APP as timeout handler, right?  Thanks...

**Pull request closed without merging**
