### PR TITLE
Disable room creation on message input

### PR DESCRIPTION
**Pull request by bhardwajaditya**
https://github.com/WideChat/Rocket.Chat/issues/1029

Rocket.Chat Server PR - https://github.com/WideChat/Rocket.Chat/pull/1036

Usage:

Add the following code in the integration script to test

RocketChat(function () {
	this.dropTriggerMessage();
});

### CODE REVIEW

**Comment by ear-dev** [comment]
@bhardwajaditya can you show me where it is that this will be disabled for brazil CX bots?

**Comment by ear-dev** [comment]
@bhardwajaditya How can I test this?  I'm not sure how to get into the condition where the room is closed, but the composer is available for typing.  Do you have a strategy or this?

**Comment by bhardwajaditya** [comment]
@ear-dev I manually enable the composer by manipulating the store state to test this functionality.

**Comment by ear-dev** [comment]
@bhardwajaditya can you describe here how you manually manipulate the store state to test this please?  Thanks.

**Comment by ear-dev** [comment]
@bhardwajaditya can you resolve the new conflicts please?  thanks.....

**Comment by bhardwajaditya** [comment]
@ear-dev fixed it

**Comment by ear-dev** [comment]
@Shailesh351 can you review and test this one please.  It also includes a server PR that allow us to configure a message when we hit this scenario.  Thanks.

**Review by Shailesh351 — APPROVED** [review]
Tested and verified by the steps @bhardwajaditya provided. It's working as expected.

After https://github.com/WideChat/Rocket.Chat.Livechat/pull/119 I think we won't get in this state because we are not showing composer at all after the chat ended

**Comment by bhardwajaditya** [comment]
@Shailesh351 it will still occur because this scenario occurs when the client is not able to receive the end chat message, it remains in the intermediate state

**Comment by ear-dev** [comment]
Thanks guys!

**Pull request merged**
