### PR TITLE
Fix two tab issue for closed chats

### LINKED ISSUE #918: [BUG] Sneaky input seen in production - two tab problem
Chad and Aditya will try to debug...

Is there something about Prod???

### PR DESCRIPTION
**Pull request by bhardwajaditya**
Closes: https://github.com/WideChat/Rocket.Chat/issues/918

### CODE REVIEW

**Review by chadgoss — COMMENTED** [review]
@Shailesh351 can you please review, thanks!

**Comment by chadgoss** [comment]
Hi @bhardwajaditya can you please fix the conflicts, and @Shailesh351 can you please review? thanks!

**Comment by bhardwajaditya** [comment]
@chadgoss @Shailesh351 fixed it

**Review by Shailesh351 — COMMENTED** [review]
@bhardwajaditya For close chat, PR is looking good. As you have merged develop branch in your branch, can you please update build files again?

I sometimes noticed nothing happens on clicking the `Close Chat` button.
And on another tab, it continues showing old conversation as below.

We can handle this in separate PR as the issues are different.

Screenshot 2021-09-23 at 10 07 18 AM

**Comment by bhardwajaditya** [comment]
@Shailesh351 for the close chat button not accessible, when the two tabs sync the close function is not stored in local storage and that leads to this problem.

The second one is due to the fact that messages are tab specific data and cannot be altered by actions of other tab.

**Comment by ear-dev** [comment]
@bhardwajaditya I think I'm still seeing the timeout timer issue?

image

**Comment by bhardwajaditya** [comment]
> @bhardwajaditya I think I'm still seeing the timeout timer issue?
> 
> image

@ear-dev yeah I am seeing that, seems to be something new because in local storage the timer running is set to false.
I see the timer in some weird state and more than one timer running. Do you see the same or the timer is going down sequentially for you?

**Comment by ear-dev** [comment]
@bhardwajaditya I'll test again to see if the timer is behaving normally.......  but do you have any thoughts about what's going on or how to fix?  Thanks.

I tested again.....  and the timer is running down normally.  But I noticed that it only shows up in the first tab.

**Comment by bhardwajaditya** [comment]
@ear-dev looking into this issue. Is this a blocker for this PR?

**Comment by ear-dev** [comment]
@bhardwajaditya that is a good question......  I think it might be a blocker because I did once get into a condition where after closing a chat, and then starting another chat, that timer went off after about 20 seconds, instead of the configured 5 minutes from SF.  That's a pretty bad UX.  Probably it had to to do with the combination of tabs being open, and which one controlled the timer and when.

**Comment by bhardwajaditya** [comment]
@ear-dev yes you are right. On it

**Comment by ear-dev** [comment]
Hi @bhardwajaditya any status on this one?  Steve really wants to get this 'session without a welcome event' issue resolved, and we believe that this will resolve maybe half of those instances.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev this is an issue due to the fact that clear timeouts don't work as of now. I see that it's an issue without this change as well so may be I can resolve it separately since it's an existing behaviour. I tried it but it would some more time to ensure it's fixed for all scenarios

**Comment by ear-dev** [comment]
@bhardwajaditya clear timeouts does not work in what way?  Resetting the timeout does seem to work, after the visitor types another message....  but are you saying that after a chat is closed, under any circumstances, the timer will continue to run if the visitor does not close the tab?  Up to now I've only seen this in a two tab scenario.

Maybe you are saying that it's currently an issue in Prod already, and not due to your fixes.  In which case, yeah, maybe we should consider deploying this and making a new story...

**Comment by bhardwajaditya** [comment]
@ear-dev yes this was reported by Shailesh along with process message in same order story. So yes this is an existing prod behaviour.

**Pull request merged**
